# Generated by Django 4.1.6 on 2023-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
