# Generated by Django 4.1.6 on 2023-02-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_registration_first_name_registration_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
