# Generated by Django 4.1.6 on 2023-02-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='service',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
