# Generated by Django 4.1.6 on 2023-02-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_registration_address_registration_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
